name: myapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0' # Updated SDK constraint

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  go_router: ^14.2.0
  google_fonts: ^6.2.1
  provider: ^6.1.2
  firebase_core: ^3.3.0
  firebase_auth: ^5.1.3
  cloud_firestore: ^5.1.0
  firebase_storage: ^12.1.2
  intl: ^0.19.0
  url_launcher: ^6.3.0
  image_picker: ^1.1.2
  geolocator: ^12.0.0
  fl_chart: ^0.68.0
  timeline_tile: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
