// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpvooFMUgulKy7oMG0vN3yPIYLt2LyLDs',
    appId: '1:160803873628:web:402a3ad7638ad7e0c6d799',
    messagingSenderId: '160803873628',
    projectId: 'bubble-new-70fa8',
    authDomain: 'bubble-new-70fa8.firebaseapp.com',
    storageBucket: 'bubble-new-70fa8.firebasestorage.app',
    measurementId: 'G-D66DL3T75C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB8NZfJwPITrUDEeIsAqpTJu9P-0jwW-io',
    appId: '1:160803873628:android:6137faf3c000e0b7c6d799',
    messagingSenderId: '160803873628',
    projectId: 'bubble-new-70fa8',
    storageBucket: 'bubble-new-70fa8.firebasestorage.app',
  );
}
